project_name: talhelper
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/budimanjojo/talhelper/cmd.version={{.Version}}
  - id: talhelper-windows-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/budimanjojo/talhelper/cmd.version={{.Version}}
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"

aurs:
  - name: talhelper-bin
    homepage: "https://github.com/budimanjojo/talhelper"
    description: "A tool to help creating Talos cluster in GitOps way."
    maintainers:
      - Budiman Jojo <budimanjojo at gmail dot com>
    license: "BSD-3-Clause"
    skip_upload: "auto"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/talhelper-bin.git"
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/LICENSE"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

scoop:
  url_template: 'https://github.com/dedene/talhelper/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
  bucket:
    owner: dedene
    name: talhelper
    branch: master
    pull_request:
      enabled: false
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/budimanjojo/talhelper"
  description: "A tool to help creating Talos kubernetes cluster "
  license: BSD-3
  depends: ["sops"]